services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: whatsapp_clone
      PG_DATA: /var/lib/postgresql/data
    ports:
      - "5433:5432"
    volumes:
      - postgres:/data/postgres
    networks:
      - whatsapp_network
    restart: unless-stopped

  keycloak:
    container_name: keycloak-wac
    image: quay.io/keycloak/keycloak:latest
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - whatsapp_network
    command:
      - "start-dev"

networks:
  whatsapp_network:
    driver: bridge


volumes:
  postgres:
    driver: local